### Verbo GET - listar todos
GET http://localhost:8000/funcionario/ HTTP/1.1

### Verbo GET - listar um
GET http://localhost:8000/funcionario/10 HTTP/1.1

### Verbo POST - adicionar
POST http://127.0.0.1:8000/funcionario/ HTTP/1.1
content-type: application/json

{
    "nome": "Valdir Vinilson",
    "cpf": "11111111111",
    "telefone": "35741269857",
    "senha": "Burzum",
    "matricula": "1478523690",
    "grupo": 1
}

### Verbo PUT - atualizar
PUT http://127.0.0.1:8000/funcionario/2 HTTP/1.1
content-type: application/json

{
    "nome": "Jaiminho Maihento",
    "cpf": "22333333999",
    "telefone": "14785201478",
    "senha": "Guittarrrra",
    "matricula": "1122336658",
    "grupo": 2
}

### Verbo DELETE - deletar
DELETE http://127.0.0.1:8000/funcionario/3 HTTP/1.1