### Verbo GET - listar todos
GET http://localhost:8000/cliente/ HTTP/1.1
x-token: TokenAcesso
x-key: KeyAcesso

### Verbo GET - listar todos
curl-X 'GET' \
    'http://localhost:8000/funcionario/' \
    -H 'accept: application/json' \
    -H 'x-token: TokenAcesso' \
    -H 'x-key: KeyAcesso'

### Verbo GET - listar um
GET http://localhost:8000/cliente/10 HTTP/1.1

### Verbo POST - adicionar
POST http://127.0.0.1:8000/cliente/ HTTP/1.1
content-type: application/json

{
    "nome": "leonardo",
    "cpf": "11111111111",
    "telefone": "14785236985",
    "compra_fiado": 2,
    "dia_fiado": 25,
    "senha": "123"
}

### Verbo PUT - atualizar
PUT http://127.0.0.1:8000/cliente/2 HTTP/1.1
content-type: application/json

{
    "nome": "vargster",
    "cpf": "33333333333",
    "telefone": "45454545454",
    "compra_fiado": 1,
    "dia_fiado": 5,
    "senha": "senha"
}

### Verbo DELETE - deletar
DELETE http://127.0.0.1:8000/cliente/3 HTTP/1.1