### Verbo GET - listar todos
GET http://localhost:8000/produto/ HTTP/1.1
x-token: TokenAcesso
x-key: KeyAcesso

### Verbo GET - listar todos
curl-X 'GET' \
    'http://localhost:8000/funcionario/' \
    -H 'accept: application/json' \
    -H 'x-token: TokenAcesso' \
    -H 'x-key: KeyAcesso'
    
### Verbo GET - listar um
GET http://localhost:8000/produto/10 HTTP/1.1

### Verbo POST - adicionar
POST http://127.0.0.1:8000/produto/ HTTP/1.1
content-type: application/json

{
    "nome": "banana",
    "descricao": "é amarela e gosta de dançar",
    "foto": "O que coloco aqui?",
    "valor_unitario": 2.50
}

### Verbo PUT - atualizar
PUT http://127.0.0.1:8000/produto/2 HTTP/1.1
content-type: application/json

{
    "nome": "abacaxi",
    "descricao": "é um abacaxi",
    "foto": "pense num abacaxi",
    "valor_unitario": 1.50
}

### Verbo DELETE - deletar
DELETE http://127.0.0.1:8000/produto/3 HTTP/1.1